# Generated by Django 3.2.7 on 2021-09-20 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_borrowed', models.BooleanField(blank=True, default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('std_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
