# Generated by Django 3.2.7 on 2021-09-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0007_alter_image_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
